import jsPDF from "jspdf";

import type { Book } from "../data/books";

export function createBookPdf(
  book: Book
) {
  const pdf = new jsPDF();

  const margin = 20;

  pdf.setFillColor(20, 19, 17);
  pdf.rect(
    0,
    0,
    210,
    297,
    "F"
  );

  pdf.setTextColor(
    238,
    230,
    211
  );

  pdf.setFontSize(28);

  pdf.text(
    "BOOK BANK",
    margin,
    35
  );

  pdf.setFontSize(20);

  const titleLines =
    pdf.splitTextToSize(
      book.title,
      170
    );

  pdf.text(
    titleLines,
    margin,
    70
  );

  pdf.setFontSize(13);

  pdf.text(
    `By ${book.author}`,
    margin,
    100
  );

  pdf.text(
    `${book.genre} • ${book.year}`,
    margin,
    115
  );

  pdf.setDrawColor(
    180,
    150,
    85
  );

  pdf.line(
    margin,
    130,
    190,
    130
  );

  pdf.setFontSize(12);

  const description =
    pdf.splitTextToSize(
      book.description,
      170
    );

  pdf.text(
    description,
    margin,
    150
  );

  pdf.setFontSize(11);

  pdf.text(
    `Language: ${book.language}`,
    margin,
    200
  );

  pdf.text(
    `Pages: ${book.pages}`,
    margin,
    212
  );

  pdf.text(
    `ISBN: ${book.isbn}`,
    margin,
    224
  );

  pdf.setFontSize(9);

  pdf.text(
    "Digital edition generated by Book Bank.",
    margin,
    270
  );

  return pdf;
}

export function downloadBookPdf(
  book: Book
) {
  const pdf =
    createBookPdf(book);

  const safeName =
    book.title
      .replace(
        /[^a-z0-9]+/gi,
        "-"
      )
      .toLowerCase();

  pdf.save(
    `${safeName}.pdf`
  );
}
